image:
  - Ubuntu2004
install:
  - sh: git submodule update --init --recursive
  - sh: export DEBIAN_FRONTEND=noninteractive
  - sh: export PATH="$HOME/.local/bin:$PATH"
  - sh: python3 -m pip install pip && python3 -m pip install tox
build_script:
  - sh: tox
