image:
  - Ubuntu2004

environment:
  matrix:
    - PYTHON: "3.8"
    - PYTHON: "3.9"
    - PYTHON: "3.10"
    - PYTHON: "3.11"

install:
  - . $HOME/venv${PYTHON}/bin/activate && python -m pip install --upgrade pip && python --version

build_script:
  - echo "build"

test_script:
  - echo "test"

deploy_script:
  - echo "deploy"
