image:
  - Ubuntu2004

environment:
  matrix:
    - PYTHON: "3.8"
    - PYTHON: "3.9"
    - PYTHON: "3.10"
    - PYTHON: "3.11"

install:
  - . $HOME/venv${PYTHON}/bin/activate && python -m pip install --upgrade pip build && python --version
  - env | grep "APPVEYOR"

build_script:
  - . $HOME/venv${PYTHON}/bin/activate && python -m build

test_script:
  - . $HOME/venv${PYTHON}/bin/activate && python -m pip install -r requirements.txt && pytest

deploy_script:
  - echo "deploy"

artifacts:
  - path: dist/docker-inside-*.tar.gz
